/**
 * Tailwind CSS Configuration with custom color palette from colors.ts
 */
import { Config } from 'tailwindcss';

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#076ae0',
        primaryDark: '#0554b8',
        primaryLight: '#3d8ee8',
        secondary: '#ffb800',
        secondaryDark: '#e6a600',
        secondaryLight: '#ffc633',
        background: '#FFFFFF',
        backgroundLight: '#F5F5F5',
        backgroundDark: '#E0E0E0',
        text: '#000000',
        textLight: '#666666',
        textMuted: '#999999',
        textPlaceholder: '#CCCCCC',
        textSecondary: '#4A4A4A',
        border: '#E5E5E5',
        borderLight: '#F0F0F0',
        borderDark: '#D0D0D0',
        borderError: '#EF4444',
        inputBackground: '#FAFAFA',
        buttonPrimary: '#ffb800',
        buttonSecondary: '#ffffff',
        buttonText: '#FFFFFF',
        buttonTextSecondary: '#000000',
        buttonDisabled: '#CCCCCC',
        google: '#DB4437',
        apple: '#000000',
        success: '#10B981',
        successLight: '#D1FAE5',
        successBackground: '#ECFDF5',
        error: '#EF4444',
        errorLight: '#FCA5A5',
        errorBackground: '#FEE2E2',
        warning: '#F59E0B',
        warningLight: '#FCD34D',
        warningBackground: '#FEF3C7',
        info: '#3B82F6',
        infoLight: '#93C5FD',
        infoBackground: '#DBEAFE',
        shadow: '#000000',
        shadowLight: '#FFD60A',
        separator: '#e0e0e0',
        separatorDark: '#3a3a3a',
        white: '#FFFFFF',
        black: '#000000',
        gray: '#9CA3AF',
        grayLight: '#F3F4F6',
        grayDark: '#4B5563',
        transparent: 'transparent',
      },
    },
  },
  plugins: [],
} satisfies Config;
